/**
 * Login
 */
export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME';
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD';
export const RESET_LOGIN_CREDENTIALS = 'RESET_LOGIN_CREDENTIALS';

/**
 * Authentication
 */
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

/**
 * Register
 */
export const CHANGE_REGISTER_FIRSTNAME = 'CHANGE_REGISTER_FIRSTNAME';
export const CHANGE_REGISTER_LASTNAME = 'CHANGE_REGISTER_LASTNAME';
export const CHANGE_REGISTER_DOB = 'CHANGE_REGISTER_DOB';
export const CHANGE_REGISTER_EMAIL = 'CHANGE_REGISTER_EMAIL';
export const CHANGE_REGISTER_USERNAME = 'CHANGE_REGISTER_USERNAME';
export const CHANGE_REGISTER_PASSWORD = 'CHANGE_REGISTER_PASSWORD';
export const CHANGE_REGISTER_PASSWORD2 = 'CHANGE_REGISTER_PASSWORD2';
export const CHANGE_REGISTER_DESCRIPTION = 'CHANGE_REGISTER_DESCRIPTION';
export const RESET_REGISTER_CREDENTIALS = 'RESET_REGISTER_CREDENTIALS';

/**
 * Job
 */
export const SEARCH_JOB = 'SEARCH_JOB';
export const LOCATION_TEXT_CHANGED = 'LOCATION_TEXT_CHANGED';
export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const JOB_DETAILS = 'JOB_DETAILS';

/**
 * Alerts
 */
export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';
export const SET = 'SET';
export const RESET = 'RESET';
export const SET_DISLIKE_JOB_ALERT = 'SET_DISLIKE_JOB_ALERT';

/**
 * PILLS
 */
export const ACTIVATE_JOB_LIKE_PILL = 'ACTIVATE_JOB_LIKE_PILL';

/**
 * Alerts
 */
export const SET_LIKED_ALERT = 'SET_LIKED_ALERT';
export const SET_ALREADY_LIKED_ALERT = 'SET_ALREADY_LIKED_ALERT';

/**
 * User
 */
export const GET_JOBS_LIKED = 'GET_JOBS_LIKED';

