/**
 * Authentication
 */
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

/**
 * Search bar
 */
export const SEARCH_JOB_START_LOADING = 'SEARCH_JOB_START_LOADING';
export const SEARCH_JOB_STOP_LOADING = 'SEARCH_JOB_STOP_LOADING';

/**
 * Job
 */
export const SEARCH_JOB = 'SEARCH_JOB';
export const LOCATION_TEXT_CHANGED = 'LOCATION_TEXT_CHANGED';
export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const JOB_DETAILS = 'JOB_DETAILS';

/**
 * PILLS
 */
export const ACTIVATE_JOBS_LIKED_PILL = 'ACTIVATE_JOBS_LIKED_PILL';
export const ACTIVATE_JOBS_BOOKMARKED_PILL = 'ACTIVATE_JOBS_BOOKMARKED_PILL';
export const ACTIVATE_JOBS_DISLIKED_PILL = 'ACTIVATE_JOBS_DISLIKED_PILL';
export const DEACTIVATE_ALL_PILLS = 'DEACTIVATE_ALL_PILLS';

/**
 * Alerts
 */
export const SET_LIKE_JOB_ALERT = 'SET_LIKE_JOB_ALERT';
export const SET_ALREADY_LIKED_JOB_ALERT = 'SET_ALREADY_LIKED_JOB_ALERT';
export const SET_DISLIKE_JOB_ALERT = 'SET_DISLIKE_JOB_ALERT';
export const SET_ALREADY_DISLIKED_JOB_ALERT = 'SET_ALREADY_DISLIKED_JOB_ALERT';
export const SET_BOOKMARK_JOB_ALERT = 'SET_BOOKMARK_JOB_ALERT';
export const SET_UNBOOKMARK_JOB_ALERT = 'SET_UNBOOKMARK_JOB_ALERT';
export const SET_ALREADY_BOOKMARKED_JOB_ALERT = 'SET_ALREADY_BOOKMARKED_JOB_ALERT';
export const SET_CANNOT_BOOKMARK_JOB_ALERT = 'SET_CANNOT_BOOKMARK_JOB_ALERT';
export const SET_CANNOT_REMOVE_LIKED_JOB_ALERT = 'SET_CANNOT_REMOVE_LIKED_JOB_ALERT';
export const SET_CANNOT_REMOVE_DISLIKED_JOB_ALERT = 'SET_CANNOT_REMOVE_DISLIKED_JOB_ALERT';
export const SET_CANNOT_REMOVE_BOOKMARKED_JOB_ALERT = 'SET_CANNOT_REMOVE_BOOKMARKED_JOB_ALERT';
export const REMOVED_LIKED_JOB_FROM_LIST_ALERT = 'REMOVED_LIKED_JOB_FROM_LIST_ALERT';
export const REMOVED_DISLIKED_JOB_FROM_LIST_ALERT = 'REMOVED_DISLIKED_JOB_FROM_LIST_ALERT';
export const REMOVED_BOOKMARKED_JOB_FROM_LIST_ALERT = 'REMOVED_BOOKMARKED_JOB_FROM_LIST_ALERT';

/**
 * User
 */
export const GET_JOBS_LIKED = 'GET_JOBS_LIKED';
export const GET_JOBS_DISLIKED = 'GET_JOBS_DISLIKED';
export const GET_JOBS_BOOKMARKED = 'GET_JOBS_BOOKMARKED';

