# Generated by Django 2.2.7 on 2019-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField()),
                ('type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('company_name', models.CharField(max_length=200)),
                ('company_website', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company_logo', models.ImageField(upload_to='')),
                ('how_to_apply', models.TextField()),
            ],
        ),
    ]
