# Generated by Django 2.2.7 on 2019-12-08 05:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_uuid',
            field=models.UUIDField(default=uuid.UUID('7061832b-3f8d-47ab-8071-89009f52ee54'), editable=False),
        ),
    ]
