# Generated by Django 2.2.7 on 2019-12-09 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_uuid',
            field=models.UUIDField(default=uuid.UUID('3c13e3e9-8d3e-46e5-846d-2c6c7ad24bd9'), editable=False),
        ),
    ]
