# Generated by Django 2.2.7 on 2019-12-02 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_website',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.TextField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters and "-" are allowed.')]),
        ),
    ]
